spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

cors.allowed.origin=${CORS_ALLOWED_ORIGIN}
server.port=${PORT}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=test67pochta@gmail.com
spring.mail.password=cmtkudjcpjrwlzji
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

jwt.secret=x11cDjk8J012juy49278gh2bk4loKiuIy4567jml5kl766kj5jhPgb56nk2dj7fs090QLGh9kzFpr784gbNas9dkMjdAK4
jwt.lifetime=3600000