spring.application.name=brassbook-backend

#spring.datasource.url=jdbc:h2:file:./data/brassbook
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

spring.datasource.url=jdbc:postgresql://localhost:5432/brassbook
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=test67pochta@gmail.com
spring.mail.password=cmtkudjcpjrwlzji
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=x11cDjk8J012juy49278gh2bk4loKiuIy4567jml5kl766kj5jhPgb56nk2dj7fs090QLGh9kzFpr784gbNas9dkMjdAK4
jwt.lifetime=3600000